env:
 - CABALVER=1.22 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=head GHCVER=head

matrix:
  allow_failures:
    - env: CABALVER=head GHCVER=head

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cabal update

  - travis_retry sudo apt-get install alex-3.1.4
  - export PATH=/opt/alex/3.1.4/bin:$PATH

script:
  - git clone https://github.com/osa1/hslua

  # Compile and link using built-in Lua
  - cabal install --disable-documentation
  - cabal test

  # Clean stuff
  - cabal clean
  - ghc-pkg unregister hslua

  # Install LuaJIT 2.0.3
  - wget http://luajit.org/download/LuaJIT-2.0.3.tar.gz
  - tar -xf LuaJIT-2.0.3.tar.gz
  - cd LuaJIT-2.0.3
  - sed -i 's/^TARGET_CC= $(STATIC_CC)/TARGET_CC= $(DYNAMIC_CC)/g' src/Makefile
  - make
  - sudo make install
  - cd ..

  # Install Lua 5.1.5
  - wget http://www.lua.org/ftp/lua-5.1.5.tar.gz
  - tar -xf lua-5.1.5.tar.gz
  - cd lua-5.1.5
  - sed -i 's/^CFLAGS= -O2 -Wall/CFLAGS= -O2 -Wall -fPIC/' src/Makefile
  - make linux
  - sudo make install
  - cd ..

  # Compile and link using system-wide Lua 5.1.5
  - cabal install -fsystem-lua
  - cabal test

  # Clean stuff
  - cabal clean
  - ghc-pkg unregister hslua

  # Compile and link using system-wide LuaJIT
  - cabal install -fsystem-lua -fluajit
  - cabal test

notifications:
  email:
    recipients: omeragacan@gmail.com
    on_success: change
    on_failure: change
